### ISSUE TITLE
Functions for identifying the parameters of distributions are not directly accessible

### ISSUE THREAD

**Issue by aakhmetz** [gitMarcH/bootComb#1]
After loading the package with ```library(bootComb)``` command, I wish to use, e.g., the function `identifyGammaPars`, but I get the message:
```
Error in identifyGammaPars(1, 16, alpha = 0.1): could not find function "identifyGammaPars"
Traceback:
```

**Comment by gitMarcH** [comment]
Hi,

The error message is triggered because `identifyGammaPars` is not an exported function -- you need to use triple colons to access it: `bootComb:::identifyGammaPars(1, 16, alpha = 0.1)`.

Alternatively use `getGammaFromCI` which is an exported function -- it uses `identifyGammaPars` to get the distribution parameter estimates but in addition will return sampling, density, distribution and quantile functions for the Gamma distribution with these parameters. But you can just access the parameter estimates via `$pars`; this will give exactly the same output as the call to `identifyGammaPars`: `getGammaFromCI(1,16,alpha=0.1)$pars` .

Hope this helps.
